2018-12-12 23:31:46,646 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-12 23:37:51,949 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-12 23:44:44,726 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-12 23:47:49,959 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-12 23:50:53,941 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-12 23:53:34,463 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-13 00:03:31,858 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-13 00:20:27,087 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-13 00:30:14,325 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-13 00:31:43,639 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-13 00:32:32,780 - logs/main.logs:63 - ERROR - TABS:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/poolminer_test.py", line 206, in poolminer_tab
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 772, in __init__
    self.streams)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 316, in validate_dynamic_argspec
    unassigned=unassigned))
KeyError: "Callable '<bound method poolminer_tab.<locals>.Poolminer.view_topN of <scripts.dashboards.streaming.poolminer_test.poolminer_tab.<locals>.Poolminer object at 0x7f12223256a0>>' missing keywords to accept stream parameters: start_date,end_date"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/main.py", line 56, in aion_analytics
    pm = yield poolminer_tab()
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/types.py", line 243, in wrapped
    coro = func(*args, **kwargs)
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/poolminer_test.py", line 225, in poolminer_tab
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/utils/myutils.py", line 88, in tab_error_flag
    print('IN POOLMINER')
BrokenPipeError: [Errno 32] Broken pipe
2018-12-13 00:41:19,860 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-13 00:43:21,811 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-13 01:04:07,971 - logs/main.logs:15 - WARNING - logs/main.logs
2018-12-13 01:06:06,434 - logs/main.logs:15 - WARNING - logs/main.logs
