2019-01-09 23:00:38,117 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:01:45,594 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:08:17,537 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:25:01,639 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:26:33,426 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:26:33,433 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:26:33,433 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:27:50,437 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:28:14,318 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:29:14,820 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:30:02,795 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-09 23:30:40,900 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-09 23:30:40,900 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-09 23:32:23,088 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-09 23:32:52,383 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-09 23:33:22,419 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:33:44,581 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:50:25,294 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:51:09,079 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:51:42,851 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:52:37,967 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:56:22,332 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:56:22,333 - logs/main.logs:52 - ERROR - WEBSERVER LAUNCH:
Traceback (most recent call last):
  File "main.py", line 47, in launch_server
    server = Server({'/': aion_analytics}, num_procs=1, port=5006)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/bokeh/server/server.py", line 372, in __init__
    applications[k] = Application(FunctionHandler(v))
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/bokeh/application/handlers/function.py", line 101, in __init__
    _check_callback(func, ('doc',))
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/bokeh/util/callback_manager.py", line 21, in _check_callback
    raise ValueError(error_msg % (", ".join(fargs), formatted_args))
ValueError: Callback functions must have signature func(doc), got func()
2019-01-09 23:56:38,040 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-09 23:57:55,604 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-10 00:02:15,662 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-10 00:02:25,548 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-10 00:02:25,548 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-10 00:02:37,902 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-10 00:02:37,902 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-10 00:02:37,902 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-10 00:07:32,291 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-10 00:14:56,122 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-10 00:15:45,503 - logs/main.logs:20 - WARNING - logs/main.logs
2019-01-10 00:16:12,916 - aion-analytics/logs/main.logs:20 - WARNING - aion-analytics/logs/main.logs
2019-01-10 00:16:35,108 - logs/main.logs:20 - WARNING - logs/main.logs
